sudo: false
dist: trusty

addons:
  chrome: stable

language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - $HOME/.npm

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g yarn
  - npm install -g phantomjs-prebuilt
  - phantomjs --version
  - yarn global add greenkeeper-lockfile@1
  - yarn global add bower

install:
  - yarn

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - npm run lint
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
